[package]
name = "nightcycle/midas"
description = "Turn every game you touch to gold with a comprehensive analytics suite!"
version = "2.0.4"
authors = ["CJ Oyer <coyer@nightcycle.us>"]
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"
exclude = ["Packages", ".vscode"]

[dependencies]
Signal = "nightcycle/signal@^1.0.2"
Maid = "nightcycle/maid@1.1.4"
NetworkUtil = "nightcycle/network-util@1.7.0"
TableUtil = "nightcycle/table-util@1.1.0"
ServiceProxy = "nightcycle/service-proxy@1.0.0"
CompressionUtil = "nightcycle/compression-util@4.1.1"
Queue = "nightcycle/queue@2.2.0"
HashUtil = "boatbomber/hashlib@1.0.0"
